Update docfx.json
MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp pull request #16
Opened 2018-06-19 11:11 UTC by v-pomanv

2018-06-19 11:14 UTC, nivnar commented
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[server-2013/lync-server-2013-managing-watcher-nodes.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-managing-watcher-nodes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-managing-watcher-nodes?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-managing-watcher-nodes.md)
[server-2013/lync-server-2013-branch-site-resiliency-requirements.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-branch-site-resiliency-requirements.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-branch-site-resiliency-requirements?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-branch-site-resiliency-requirements.md)
[server-2013/lync-server-2013-planning-for-private-telephone-lines.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-planning-for-private-telephone-lines.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-planning-for-private-telephone-lines?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-planning-for-private-telephone-lines.md)
[server-2013/remove-csvoicenormalizationrule.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/remove-csvoicenormalizationrule.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/remove-csvoicenormalizationrule?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Fremove-csvoicenormalizationrule.md)
[server-2013/lync-server-2013-using-the-office-customization-tool-oct.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-using-the-office-customization-tool-oct.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-using-the-office-customization-tool-oct?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-using-the-office-customization-tool-oct.md)
[server-2013/lync-server-2013-testing-user-presence-publishing-and-subscribing.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-testing-user-presence-publishing-and-subscribing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-testing-user-presence-publishing-and-subscribing?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-testing-user-presence-publishing-and-subscribing.md)
[server-2013/lync-server-2013-focusjoinsandleaves-table.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-focusjoinsandleaves-table.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-focusjoinsandleaves-table?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-focusjoinsandleaves-table.md)
[server-2013/lync-server-2013-configuring-dial-in-conferencing.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-configuring-dial-in-conferencing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configuring-dial-in-conferencing?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-configuring-dial-in-conferencing.md)
[server-2013/lync-server-2013-first-steps-before-you-start-migrating-users-from-lync-online-to-lync-on-premises.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-first-steps-before-you-start-migrating-users-from-lync-online-to-lync-on-premises.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-first-steps-before-you-start-migrating-users-from-lync-online-to-lync-on-premises?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-first-steps-before-you-start-migrating-users-from-lync-online-to-lync-on-premises.md)
[server-2013/lync-server-2013-testing-user-connection-to-exchange-um.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-testing-user-connection-to-exchange-um.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-testing-user-connection-to-exchange-um?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-testing-user-connection-to-exchange-um.md)
[server-2013/lync-server-2013-integrating-lync-server-and-outlook-web-app-2013.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-integrating-lync-server-and-outlook-web-app-2013.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-integrating-lync-server-and-outlook-web-app-2013?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-integrating-lync-server-and-outlook-web-app-2013.md)
[server-2013/lync-server-2013-planning-for-persistent-chat-server.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-planning-for-persistent-chat-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-planning-for-persistent-chat-server?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-planning-for-persistent-chat-server.md)
[server-2013/lync-server-2013-branch-site-resiliency-features.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-branch-site-resiliency-features.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-branch-site-resiliency-features?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-branch-site-resiliency-features.md)
[server-2013/lync-server-2013-using-the-monitoring-dashboard.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-using-the-monitoring-dashboard.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-using-the-monitoring-dashboard?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-using-the-monitoring-dashboard.md)
[server-2013/lync-server-2013-configuring-default-picture-options.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/lync-server-2013-configuring-default-picture-options.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/lync-server-2013-configuring-default-picture-options?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Flync-server-2013-configuring-default-picture-options.md)
[server-2013/remove-csvoicemailreroutingconfiguration.md](https://github.com/v-pomanv/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp/blob/master/server-2013/remove-csvoicemailreroutingconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/ja-jp/office/lync-server-2013/remove-csvoicemailreroutingconfiguration?branch=pr-ja-jp-16) | [Details](#user-content-server-2013%2Fremove-csvoicemailreroutingconfiguration.md)
[server-2013/lync-server-2013-finalizing-and-implementing-the-topology-design.md](https://github.com/v-p [...]

2018-06-19 17:42 UTC, nivnar requested changes
Please update author and ms.author values to 'SerdarSoysal'

2018-06-26 06:32 UTC, nivnar commented
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp, working directory: W:\sprf-s, target branch: master, target branch commit: 621f9283c30f812e9cd8e159d22a4ba9cca4534c, source branch: 0c3e63c2a7bacb06d5bd16f61b239754/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201806260632350003-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=R446wy5y7N5uy1oBiHBLYSTRckyGpmowI7RgxWwc%2FQU%3D&st=2018-06-26T06%3A27%3A55Z&se=2018-07-27T06%3A32%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-06-26 09:15 UTC, nivnar commented
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp, working directory: W:\hci0-s, target branch: master, target branch commit: 621f9283c30f812e9cd8e159d22a4ba9cca4534c, source branch: 0c3e63c2a7bacb06d5bd16f61b239754/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201806260915026376-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=k8fCiT9pj23xc%2FRZ%2F8vBXxPA7d46J8Fw7QWAbDX%2FUoE%3D&st=2018-06-26T09%3A10%3A24Z&se=2018-07-27T09%3A15%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-06-26 10:16 UTC, nivnar commented
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp, working directory: W:\ahxc-s, target branch: master, target branch commit: 621f9283c30f812e9cd8e159d22a4ba9cca4534c, source branch: 0c3e63c2a7bacb06d5bd16f61b239754/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C26%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201806261016030626-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=d32T0OEz%2F4xAf5XBry4mgimJYtDuMgXKZj2W5VmvpQ4%3D&st=2018-06-26T10%3A11%3A23Z&se=2018-07-27T10%3A16%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-12 04:38 UTC, nivnar commented
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp, working directory: W:\e1gh-s, target branch: master, target branch commit: 621f9283c30f812e9cd8e159d22a4ba9cca4534c, source branch: 0c3e63c2a7bacb06d5bd16f61b239754/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201807120438348431-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FvZYJDNh27Ai7hTd9oh%2BEZqSqZwReI5h44OjV4dV4%2BI%3D&st=2018-07-12T04%3A33%3A55Z&se=2018-08-12T04%3A38%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-12 04:39 UTC, nivnar commented
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/MicrosoftDocs/OfficeDocs-SkypeforBusiness-Test-pr.ja-jp, working directory: W:\55cj-s, target branch: master, target branch commit: 621f9283c30f812e9cd8e159d22a4ba9cca4534c, source branch: 0c3e63c2a7bacb06d5bd16f61b239754/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5C7e25592f-fcd6-9518-53d1-4b16c8ea2040%5CPullRequest%5C201807120438464102-16%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oHWmKQu63hlvwt6bYg%2Bu8jIk%2B6EwPeaFyh7OrTu%2Be%2Bg%3D&st=2018-07-12T04%3A34%3A22Z&se=2018-08-12T04%3A39%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2018-07-12 17:27 UTC, nivnar requested changes
Shared feedback changes on missing language headers for en-us lync server 2013 tools library, Please update accordingly on ja-jp pages

2018-07-20 04:31 UTC, DanMSFT commented
Closing PR due to errors.  Intentions of this PR have been finished via a different PR.

2018-07-20 04:31 UTC, closed without merging